import type { Metadata } from "next";
import { Inter, Lato } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/shared/Sidebar";
import MainSearch from "@/components/shared/MainSearch";

// const lato = Lato({ subsets: ["latin"] });
const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="bg-primary-dark">
        <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[200px_1fr]">
          <Sidebar />
          <div className="flex flex-col">
            <MainSearch />
            <main className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
